[project]
name = "mcpscreen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai",
    "fastmcp>=2.3.4",
    "matplotlib",
    "pyaudio",
    "sounddevice",
    "numpy",
    "faster-whisper",
    "torch",
    "torchaudio",
    "noisereduce",
    "piper-tts",
    "opencv-python",
    "face-recognition",
    "onnxruntime",
    "soundfile>=0.14.0",
    "ollama>=0.6.2",
    "requests>=2.34.2",
]
